namespace: maccan-tech
name: linux-base
version: 0.0.1
readme: README.md

authors:
  - maccan-tech


description: Ansible role for linux base setup the way i like it.

license:
  - GPLv2

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: []

dependencies: {}

build_ignore: []

